### ISSUE TITLE
Processed datasets 

### ISSUE THREAD

**Issue by MingkangXiong** [robot-learning-freiburg/CL-SLAM#2]
Could you please provide the processed datasets for downloading? It quite difficult to download so many origin raw data, especially the website of OXFORD ROBOTCAR DATASET is down recently.

**Comment by vniclas** [comment]
Hi @MingkangXiong,
Thank you for your interest in our work. 

We cannot re-upload the utilized dataset due to copyright reasons. I would recommend you contact the authors of the RobotCar Dataset asking them to fix their website.

However, you can skip downloading the Cityscapes dataset if you utilize our provided model weights from pertaining.
`wget http://continual-slam.cs.uni-freiburg.de/static/models/cityscapes_masks_pretrain.zip` (wait some time if the server doesn't react immediately)
